apiVersion: v2
name: strimzi-kafka-operator
type: application
version: 0.38.0
appVersion: 0.38.0
dependencies:
  - name: strimzi-kafka-operator
    version: 0.38.0
    repository: https://strimzi.io/charts/