apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: default-cluster-issuer
  labels:
    {{- include "dev-glue.labels" . | nindent 4}}
  name: schema-registry
spec:
  ingressClassName: traefik
  rules:
    - host: sr.local.lgc
      http:
        paths:
          - backend:
              service:
                name: confluent-schema-registry
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - sr.local.lgc
      secretName: confluent-schema-registry-tls
